<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>29-手写promise-12-catch方法-异常穿透与值传递</title>
  </head>
  <body></body>
  <script>
    function Promise(executor) {
      // 添加属性
      this.PromiseState = 'pending'
      this.PromiseResult = null
      // 声明一个属性
      this.callback = []
      // 保存实例对象的this值
      const self = this
      // 执行器函数在内部是同步调用的
      function resolve(data) {
        // 增加判断状态逻辑
        if (self.PromiseState !== 'pending') {
          return
        }
        // 修改对象的状态(promiseState)
        self.PromiseState = 'fulfilled'
        // 设置对象的结果值(promiseResult)
        self.PromiseResult = data
        // 调用成功的回调函数
        if (self.callback.length > 0) {
          self.callback.forEach((item) => {
            item.onResolved(data)
          })
          // self.callback = []
        }
      }

      function reject(error) {
        if (self.PromiseState !== 'pending') {
          return
        }
        self.PromiseState = 'rejected'
        self.PromiseResult = error
        // 调用失败的回调函数
        if (self.callback.length > 0) {
          self.callback.forEach((item) => {
            item.onRejected(error)
          })
          // self.callback = []
        }
      }
      try {
        executor(resolve, reject)
      } catch (error) {
        // 修改 promise 的状态为失败
        reject(error)
      }
    }

    // 添加 then 方法
    Promise.prototype.then = function (onRejected, onRejected) {
      const self = this
      // onRejected、onRejected 兼容处理为空时候的处理
      if (typeof onRejected !== 'function') {
        onRejected = (reason) => {
          throw reason
        }
      }

      if (typeof onResolved !== 'function') {
        onResolved = (value) => value
      }
      return new Promise((resolve, reject) => {
        function callback(typeFunc) {
          try {
            let result = typeFunc(self.PromiseResult)
            if (result instanceof Promise) {
              result.then(
                (v) => {
                  resolve(v)
                },
                (e) => {
                  reject(e)
                }
              )
            } else {
              // 结果的对象状态为成功
              resolve(result)
            }
          } catch (error) {
            reject(error)
          }
        }
        if (this.PromiseState === 'fulfilled') {
          callback(onResolved)
        } else if (this.PromiseState === 'rejected') {
          callback(onRejected)
        }
        // 增加pending 的一个判断
        if (this.PromiseState === 'pending') {
          // 需要保存回调函数
          this.callback.push({
            onResolved: function () {
              // console.log('success')
              // 执行成功的回调函数
              callback(onResolved)
            },
            onRejected: function () {
              callback(onRejected)
            },
          })
        }
      })
    }

    Promise.prototype.catch = function (onRejected) {
      return this.then(undefined, onRejected)
    }
  </script>
  <script>
    let p = new Promise((resolve, reject) => {
      setTimeout(() => {
        // resolve('ok1')
        reject('error122')
      }, 1000)
    })
    const result = p
      .then()
      .then(
        (value1) => {
          return 'i am success'
        },
        (error1) => {
          console.log('error1', error1)
        }
      )
      .then(
        (res) => {
          console.log('res2', res)
        },
        (error2) => {
          console.log('error2', error2)
        }
      )
      .then((res3) => {
        console.log('res3', res3)
      })
      .catch((error) => {
        console.log(3333, error)
      })
    // console.log(1111, result)
  </script>
</html>
